defaults:
  - modules/encoder@encoder: Cond_unet_enc_Modern
  - modules/decoder@decoder: unet_dec_Modern


_target_: dlwp.model.models.unet.CubeSphereUnet
_recursive_: false
presteps: 0
input_time_dim: ${data.input_time_dim}
output_time_dim: ${data.output_time_dim}

# Parameters automatically overridden in train code
input_channels: 7
output_channels: 7
n_constants: 0
decoder_input_channels: 1

# some perf parameters
enable_nhwc: false
enable_healpixpad: false