defaults:
  - /model/modules/conditional_blocks@conv_block: basic_conv_block
  - /model/modules/blocks@down_sampling_block: avg_pool

_target_: dlwp.model.modules.encoder.ConditionalUNetEncoder
_recursive_: false
n_channels:
  - 64
  - 128
  - 256
n_layers:
  - 1
  - 1
  - 1
dilations:
  - 1
  - 1
  - 1