defaults:
  - conv_block: ../../modules/blocks/conv_next_block
  - down_sampling_block: ../../modules/blocks/avg_pool

_target_: dlwp.model.models.hpx_unet.UNet3PlusEncoder
_recursive_: false
n_channels:
  - 64
  - 128
  - 256
dilations:
  - 1
  - 2
  - 4