defaults:
  - /model/modules/conditional_blocks@conv_block: conv_next_block
  - /model/modules/blocks@up_sampling_block: transposed_conv_upsample
  - /model/modules/blocks@recurrent_block: null
  - /model/modules/blocks@output_layer: output_layer

_target_: dlwp.model.modules.decoder.ConditionalUNetDecoder 
_recursive_: false
# n_channels: 
#   - 34
#   - 68
#   - 136
n_channels:
  - 64
  - 128
  - 256
dilations:
  - 4
  - 2
  - 1
